---
abstract: 'Simplistic wrapper for the excellent PDF::API2 modules'
author:
  - 'Red Tree Systems, LLC'
build_requires:
  ExtUtils::MakeMaker: 6.36
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: 'public domain'
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: PDF-API2-Simple
no_index:
  directory:
    - examples
    - inc
    - t
requires:
  Carp: 0
  PDF::API2: 0
version: 1.1.5
